
export const MINIMUM_ASSET_ID_LENGTH = 16


export const REFRESH_ASSETS = 'REFRESH_ASSETS'
export const SAVE_ASSETS = 'SAVE_ASSETS'
export const SET_ASSET = 'SET_ASSET'
export const DELETE_ASSET = 'DELETE_ASSET'

export const SET_ASSET_VALUE = 'SET_ASSET_VALUE'
export const SET_ASSET_ATTRIBUTE = 'SET_ASSET_ATTRIBUTE'
export const SET_ASSET_CONNECTION = 'SET_ASSET_CONNECTION'
export const SET_ASSET_CONNECTION_ATTRIBUTE = 'SET_ASSET_CONNECTION_ATTRIBUTE'

export const FILL_ASSET_NAME = 'FILL_ASSET_NAME'

export const INSERT_ASSET_VERTEX = 'INSERT_ASSET_VERTEX'
export const DELETE_ASSET_VERTEX = 'DELETE_ASSET_VERTEX'

export const UPLOAD_ASSETS_CSV = 'UPLOAD_ASSETS_CSV'
