import assetTypeById from './datasets/assetTypeById.json'


export const CONTENT_PADDING = 24
export const NAVIGATION_DRAWER_WIDTH = 192
export const INFORMATION_DRAWER_WIDTH = 512
export const RIGHT_DRAWER_MINIMUM_WIDTH = 256


export const MAXIMUM_ASSET_LIST_LENGTH = 100
export const TOOLTIP_DELAY = 500
export const DEBOUNCE_THRESHOLD_IN_MILLISECONDS = 100


export const LOG_ERROR = 'LOG_ERROR'


export const REFRESH_ASSETS = 'REFRESH_ASSETS'
export const ADD_ASSET = 'ADD_ASSET'
export const CHANGE_ASSET = 'CHANGE_ASSET'


export const REPLACE_ASSET = 'REPLACE_ASSET'
export const REPLACE_ASSETS = 'REPLACE_ASSETS'


export const EXCLUDE_ASSET_ATTRIBUTE_FILTER = 'EXCLUDE_ASSET_ATTRIBUTE_FILTER'
export const INCLUDE_ASSET_ATTRIBUTE_FILTER = 'INCLUDE_ASSET_ATTRIBUTE_FILTER'
export const SET_ASSET_ATTRIBUTE_FILTERS = 'SET_ASSET_ATTRIBUTE_FILTERS'
export const TOGGLE_ASSET_ATTRIBUTE_FILTER = 'TOGGLE_ASSET_ATTRIBUTE_FILTER'


export const SET_FOCUSING_ASSET = 'SET_FOCUSING_ASSET'


export const SET_ASSET_FILTER = 'SET_ASSET_FILTER'


export const ASSET_TYPE_BY_ID = assetTypeById
export const DEFAULT_ASSET_TYPE_ID = 'p'
export const SELECTED_ASSET_TYPE_IDS = ['l']
